# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute iOS build"
  lane :ios_firebase_development do
      build_app(
          scheme: "Development",
          archive_path: "./build/Runner.xcarchive",
          output_directory: "./build/Runner"
      )

      firebase_app_distribution(
          app: "1:463294679347:ios:5143874ebfb1cfa49dd646",
          groups: "sample_tester",
          release_notes_file: "../CHANGELOG.md",
          firebase_cli_path: "/usr/local/bin/firebase",
          ipa_path: "./build/Runner/Runner.ipa"
      )
  end

  lane :ios_firebase_production do
      build_app(
          scheme: "Production",
          archive_path: "./build/Runner.xcarchive",
          output_directory: "./build/Runner"
      )

      firebase_app_distribution(
          app: "1:463294679347:ios:3a0c1ec17219997c9dd646",
          groups: "sample_tester",
          release_notes_file: "../CHANGELOG.md",
          firebase_cli_path: "/usr/local/bin/firebase",
          ipa_path: "./build/Runner/Runner.ipa"
      )
  end

  lane :ios_testflight_development do
      build_app(
          scheme: "Development",
          archive_path: "./build/Runner.xcarchive",
          output_directory: "./build/Runner"
      )

      changelog = read_changelog(
          changelog_path: '../CHANGELOG.md',
          section_identifier: '[Change Log]'
      )

      api_key = app_store_connect_api_key(
         key_id: "YOUR_KEY_ID",
         issuer_id: "YOUR_ISSUE_ID",
         key_filepath: "./AuthKey.p8",
         duration: 1200, # optional (maximum 1200)
         in_house: false # optional but may be required if using match/sigh
     )

      upload_to_testflight(
          api_key: api_key,
          app_identifier: "com.flutter.base.dev",
          changelog: changelog
      )
  end

  lane :ios_testflight_production do
      api_key = app_store_connect_api_key(
          key_id: "YOUR_KEY_ID",
          issuer_id: "YOUR_ISSUE_ID",
          key_filepath: "./AuthKey.p8",
          duration: 1200, # optional (maximum 1200)
          in_house: false # optional but may be required if using match/sigh
      )

      build_app(
          scheme: "Production",
          archive_path: "./build/Runner.xcarchive",
          output_directory: "./build/Runner"
      )

      upload_to_testflight(
          api_key: api_key,
          app_identifier: "com.flutter.base",
      )
  end
end
